# Display a "Sponsor this project" button on GitHub repository
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - 'https://buy.polar.sh/polar_cl_Daba3yPHh6lSxkAEIurpL3KJdtAFLlgFocBdd2WBeUX'
