# Display a "Sponsor this project" button on GitHub repository
# Docs: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

custom:
  - 'https://buy.polar.sh/polar_cl_rXgdrUGO3mDHU7qDStt2Oh8oDPxe0PJJt6ByC0s6SCg'
